"""
ReportAgent  (Objective 3: Automated Actions - generate reports)

Turns the analysis + summaries into a polished report and produces two
downloadable artifacts:
  * Markdown (always)
  * PDF (via fpdf2; degrades gracefully to Markdown-only if fpdf2 unavailable)
"""
from __future__ import annotations

import time
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from agents.base import BaseAgent, Document
from config import APP_NAME


class ReportAgent(BaseAgent):
    name = "ReportAgent"

    def run(
        self,
        title: str,
        docs: List[Document],
        analysis: Dict[str, Any],
    ) -> Dict[str, Any]:
        t0 = time.time()
        md = self._build_markdown(title, docs, analysis)
        pdf_bytes: Optional[bytes] = None
        try:
            pdf_bytes = self._markdown_to_pdf(title, md)
            detail = "markdown + pdf"
        except Exception as e:  # noqa: BLE001
            detail = f"markdown only (pdf unavailable: {e})"
        self._record("generate_report", "ok", time.time() - t0, detail=detail)
        return {"markdown": md, "pdf_bytes": pdf_bytes}

    # -- markdown ----------------------------------------------------------
    @staticmethod
    def _build_markdown(title: str, docs: List[Document], analysis: Dict[str, Any]) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines: List[str] = []
        lines.append(f"# {title}")
        lines.append("")
        lines.append(f"*Generated by {APP_NAME} on {now}*")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append(analysis.get("executive_summary", "_No summary available._"))
        lines.append("")

        sentiment = analysis.get("overall_sentiment", "neutral")
        conf = analysis.get("confidence", "n/a")
        lines.append(f"**Market sentiment:** {sentiment}  |  "
                     f"**Confidence:** {conf}")
        lines.append("")

        # Market-intelligence sections. Older/heuristic payloads may use the
        # legacy keys, so fall back to them where relevant.
        sections: List[Tuple[str, List[str]]] = [
            ("Market Trends", analysis.get("market_trends", [])),
            ("Competitor Moves",
             analysis.get("competitor_moves", analysis.get("key_findings", []))),
            ("Opportunities", analysis.get("opportunities", [])),
            ("Threats", analysis.get("threats", analysis.get("risks_or_gaps", []))),
            ("Recommendations", analysis.get("recommendations", [])),
        ]
        for heading, items in sections:
            lines.append(f"## {heading}")
            for item in items or ["_None_"]:
                lines.append(f"- {item}")
            lines.append("")

        lines.append("## Source Appendix")
        for i, d in enumerate(docs, 1):
            lines.append(f"### {i}. {d.title}  _({d.source_type}, {d.char_count} chars)_")
            if d.keywords:
                lines.append(f"**Keywords:** {', '.join(d.keywords)}")
            lines.append("")
            lines.append(d.summary or d.text[:500])
            lines.append("")
        return "\n".join(lines)

    # -- pdf ---------------------------------------------------------------
    @staticmethod
    def _markdown_to_pdf(title: str, md: str) -> bytes:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        # Use the effective page width explicitly. Passing w=0 triggers a
        # "Not enough horizontal space" error in fpdf2 >= 2.8.x in some cases.
        W = pdf.epw

        def _txt(s: str) -> str:
            # fpdf core fonts are latin-1; drop unrepresentable chars
            return s.encode("latin-1", "replace").decode("latin-1")

        for raw in md.split("\n"):
            line = raw.rstrip()
            if line.startswith("# "):
                pdf.set_font("Helvetica", "B", 18)
                pdf.multi_cell(W, 9, _txt(line[2:]))
                pdf.ln(1)
            elif line.startswith("## "):
                pdf.set_font("Helvetica", "B", 14)
                pdf.ln(2)
                pdf.multi_cell(W, 8, _txt(line[3:]))
            elif line.startswith("### "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.multi_cell(W, 7, _txt(line[4:]))
            elif line.startswith("- "):
                pdf.set_font("Helvetica", "", 11)
                pdf.multi_cell(W, 6, _txt("  - " + line[2:]))
            elif line.startswith("*") and line.endswith("*") and len(line) > 2:
                pdf.set_font("Helvetica", "I", 10)
                pdf.multi_cell(W, 6, _txt(line.strip("*")))
            elif line == "":
                pdf.ln(2)
            else:
                pdf.set_font("Helvetica", "", 11)
                pdf.multi_cell(W, 6, _txt(line))

        # fpdf2 >= 2.x returns a bytearray from output(); normalize to bytes
        return bytes(pdf.output())
